/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-card': 'var(--bg-card)',
        'bg-glass': 'var(--bg-glass)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'accent-blue': 'var(--accent-blue)',
        'accent-blue-strong': 'var(--accent-blue-strong)',
        'accent-purple': 'var(--accent-purple)',
        'accent-purple-strong': 'var(--accent-purple-strong)',
        risk: 'var(--risk)',
        warning: 'var(--warning)',
        success: 'var(--success)',
        analytics: 'var(--analytics)',
        architecture: 'var(--architecture)',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        surface: { DEFAULT: 'hsl(var(--surface))', hover: 'hsl(var(--surface-hover))' },
        panel: { DEFAULT: 'hsl(var(--panel))', border: 'hsl(var(--panel-border))' },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar))',
          hover: 'hsl(var(--sidebar-hover))',
          active: 'hsl(var(--sidebar-active))',
          foreground: 'hsl(var(--sidebar-foreground))',
          muted: 'hsl(var(--sidebar-muted))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          bg: 'hsl(var(--success-bg))',
          foreground: 'hsl(var(--success-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          bg: 'hsl(var(--warning-bg))',
          foreground: 'hsl(var(--warning-foreground))',
        },
        danger: {
          DEFAULT: 'hsl(var(--danger))',
          bg: 'hsl(var(--danger-bg))',
          foreground: 'hsl(var(--danger-foreground))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
          bg: 'hsl(var(--info-bg))',
          foreground: 'hsl(var(--info-foreground))',
        },
        risk: {
          critical: { DEFAULT: 'hsl(var(--risk-critical))', bg: 'hsl(var(--risk-critical-bg))' },
          high: { DEFAULT: 'hsl(var(--risk-high))', bg: 'hsl(var(--risk-high-bg))' },
          medium: { DEFAULT: 'hsl(var(--risk-medium))', bg: 'hsl(var(--risk-medium-bg))' },
          low: { DEFAULT: 'hsl(var(--risk-low))', bg: 'hsl(var(--risk-low-bg))' },
        },
        stage: {
          extraction: 'hsl(var(--stage-extraction))',
          'static-analysis': 'hsl(var(--stage-static-analysis))',
          enterprise: 'hsl(var(--stage-enterprise))',
          'ai-boundaries': 'hsl(var(--stage-ai-boundaries))',
          'ai-readiness': 'hsl(var(--stage-ai-readiness))',
          'ai-adrs': 'hsl(var(--stage-ai-adrs))',
          'ai-migration': 'hsl(var(--stage-ai-migration))',
          'ai-cost': 'hsl(var(--stage-ai-cost))',
          'ai-explain': 'hsl(var(--stage-ai-explain))',
          results: 'hsl(var(--stage-results))',
          report: 'hsl(var(--stage-report))',
          manifest: 'hsl(var(--stage-manifest))',
        },
        score: {
          excellent: 'hsl(var(--score-excellent))',
          good: 'hsl(var(--score-good))',
          fair: 'hsl(var(--score-fair))',
          poor: 'hsl(var(--score-poor))',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'display': ['1.75rem', { lineHeight: '1.2', fontWeight: '650', letterSpacing: '-0.025em' }],
        'h1': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
        'h2': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        'h3': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
        'h4': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-tight)' }],
        'base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
        'body-sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
        'caption': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-relaxed)' }],
        'hero': ['3rem', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.03em' }],
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        drawer: 'var(--shadow-drawer)',
        modal: 'var(--shadow-modal)',
        glass: 'var(--shadow-glass)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
        page: 'var(--duration-page)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
      },
      spacing: {
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '3': 'var(--spacing-3)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '8': 'var(--spacing-8)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        'slide-out-right': { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(100%)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'pulse-soft': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        'count-up': { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'shimmer': { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        'typing': { '0%, 100%': { opacity: '0.3' }, '50%': { opacity: '1' } },
      },
      animation: {
        'fade-in': 'fade-in var(--duration-base) var(--ease-out)',
        'fade-up': 'fade-up var(--duration-slow) var(--ease-out)',
        'slide-in-right': 'slide-in-right var(--duration-slow) var(--ease-out)',
        'slide-out-right': 'slide-out-right var(--duration-base) var(--ease-in-out)',
        'scale-in': 'scale-in var(--duration-base) var(--ease-out)',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'count-up': 'count-up 0.7s var(--ease-out)',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'typing': 'typing 1.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
